import "@/styles/globals.css";
import { headers } from "next/headers";
import dynamic from "next/dynamic";

// const PeerProvider = dynamic(() => import("@/lib/peer"), { ssr: false });
// const SocketProvider = dynamic(() => import("@/lib/socket"), { ssr: false });
import AuthContext from "@/lib/auth-context";
import { getSession } from "@/lib/auth-session";

export const metadata = {
  title: "video chat App",
  description: "Generated by create next app with typescript",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession(headers().get("cookie") ?? "");
  return (
    <html lang="en">
      <body>
        <AuthContext session={session}>
          {/* <PeerProvider> */}
          {/* <SocketProvider> */}
          <main>{children}</main>
          {/* </SocketProvider> */}
          {/* </PeerProvider> */}
        </AuthContext>
      </body>
    </html>
  );
}
