import "@/styles/globals.css";
import AuthContext from "@/lib/providers/auth-context";
import ReduxProvider from "@/lib/providers/redux-provider";

export const metadata = {
  title: "Meetly | video conference",
  description: "Generated by create next app with typescript",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <ReduxProvider>{children}</ReduxProvider>
        </AuthContext>
      </body>
    </html>
  );
}
